spring.datasource.url=jdbc:h2:mem:wishlistdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql,classpath:update_about.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.open-in-view=false

server.port=8080

# ????????? ??????????? ????????
spring.web.resources.static-locations=classpath:/static/,file:avatars/

# ????????? email (Mailtrap.io ??? ????????????)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=578a7dc28fe9a1
spring.mail.password=9b651d91219bc3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.debug=true

# Gmail SMTP (??????????????? ??? ????????????)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=spisokjelaniy@gmail.com
# spring.mail.password=Kk4952331108
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.debug=true
# spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Spring Boot Actuator ??????
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.server.port=8081

# Actuator
management.endpoints.web.access.default=allow
management.endpoint.health.probes.enabled=true

#  ????????? ?????? ??????????????????
management.metrics.tags.application=wishlist-app
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99

# JWT ????????????
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# Jasypt encryption password
jasypt.encryptor.password=7xr6O3MWouCOSXuNCF9OzhMmzZLBo3aQIvzZnUzQzRU=
