# ????????????? ???????????? ??????????
# ??? ??????????? ???????????? ????????? ???????? jasypt.encryptor.password

# ???? ?????? ? ?????????????? ????????
spring.datasource.url=jdbc:h2:mem:wishlistdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ENC(G6k2L9mX4nQ8jV7pR3tY5wE1cF2aS9dH)
spring.datasource.password=ENC(4J3rj6jOvvgY25StCteOb63FGlIsCjEnm98AkzCHXC+5aPSx5Up8iHrKbwoaLj2L)

# JPA ?????????
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql,classpath:update_about.sql

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.open-in-view=false

# ??????
server.port=8080

# ??????????? ???????
spring.web.resources.static-locations=classpath:/static/,file:avatars/

# Email ???????????? ? ?????????????? ???????? (Mailtrap.io ??? ??????????)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ENC(578a7dc28fe9a1)
spring.mail.password=ENC(2c1iPYXLXAAK1SDVAI7VvKy5W79a4+ICSvu0UdSkHJFzBmjv+XwIOnoRJN5+/7w0)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.debug=true

# Gmail SMTP (????????????????? ??? ??????????)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=ENC(spisokjelaniy@gmail.com)
# spring.mail.password=ENC(vdrXZt9HL73KrzNMMzC3tRWE5BKyy//8TyNKjKhEi7VKtvF1yBDFrTMfFE3Vv3+B)
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.debug=true
# spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Actuator ?????????
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.server.port=8081

# ???????????? Actuator
management.endpoints.web.access.default=allow
management.endpoint.health.probes.enabled=true

# ???????
management.metrics.tags.application=wishlist-app
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99

# JWT ? ????????????? ????????
jwt.secret=ENC(cIdf7DrhiAoEgpC2iD695tCtJHd2xcorQzImYABsQLOz8y5aNvB+9Wz10uPv66ZrUQbJBEevOsVULHGwmq303mFcQDt6Lm7uJ8y3zkb/Vck=)
jwt.expiration=86400000

# Jasypt ?????????
jasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256
jasypt.encryptor.key-obtention-iterations=1000
jasypt.encryptor.pool-size=1
jasypt.encryptor.provider-name=SunJCE
jasypt.encryptor.salt-generator-classname=org.jasypt.salt.RandomSaltGenerator
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
jasypt.encryptor.string-output-type=base64
